# Generated by Django 3.2.7 on 2021-10-29 01:31

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_auto_20211015_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 18, 31, 3, 617452, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 10, 28, 18, 31, 3, 617452, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='questionsubmission',
            name='points',
            field=models.IntegerField(default=-1),
        ),
    ]
