# Generated by Django 3.2.7 on 2021-10-29 01:43

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20211028_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='state',
            field=django_fsm.FSMField(default='unpublished', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 18, 43, 55, 718586, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 10, 28, 18, 43, 55, 718586, tzinfo=utc))]),
        ),
    ]
