# Generated by Django 3.2.7 on 2021-10-29 03:56

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_auto_20211028_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 20, 56, 0, 696960, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 10, 28, 20, 56, 0, 696960, tzinfo=utc))]),
        ),
    ]
