# Generated by Django 3.2.7 on 2021-10-31 03:05

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_auto_20211030_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 20, 5, 7, 429216, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 10, 30, 20, 5, 7, 429216, tzinfo=utc))]),
        ),
    ]
