# Generated by Django 3.2.7 on 2021-11-12 01:50

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_auto_20211104_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 17, 50, 40, 979170, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 11, 11, 17, 50, 40, 979170, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='gradedquestionsubmission',
            name='GradedAssignmentSubmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_question_submissions', to='assignments.gradedassignmentsubmission'),
        ),
    ]
