# Generated by Django 3.2.7 on 2021-11-12 07:51

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_auto_20211111_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignmentsubmission',
            name='index',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 23, 51, 34, 449200, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 11, 11, 23, 51, 34, 449200, tzinfo=utc))]),
        ),
    ]
