# Generated by Django 3.2.7 on 2021-11-13 00:01

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_auto_20211111_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradedquestionsubmission',
            old_name='QuestionSubmission',
            new_name='question_submission',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 16, 1, 5, 816047, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 11, 12, 16, 1, 5, 816047, tzinfo=utc))]),
        ),
    ]
