# Generated by Django 3.2.7 on 2021-11-13 01:07

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_auto_20211112_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedassignmentsubmission',
            name='submitted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 17, 7, 12, 299459, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 11, 12, 17, 7, 12, 299459, tzinfo=utc))]),
        ),
    ]
