# Generated by Django 3.2.7 on 2021-11-23 05:04

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0019_auto_20211118_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 21, 4, 30, 40850, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 11, 22, 21, 4, 30, 40850, tzinfo=utc))]),
        ),
    ]
