# Generated by Django 3.2.7 on 2021-11-23 05:14

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedquestionsubmission',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 21, 14, 39, 417625, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 11, 22, 21, 14, 39, 417625, tzinfo=utc))]),
        ),
    ]
