# Generated by Django 3.2.7 on 2021-11-30 06:28

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0022_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 22, 28, 22, 57669, tzinfo=utc), validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2021, 11, 29, 22, 28, 22, 57669, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='gradedquestionsubmission',
            name='points',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionsubmission',
            name='points',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
